### ISSUE TITLE
New config.ini

### ISSUE THREAD

**Issue by tharris9d** [FAKEHDHR/FakeHDHR_Locast#13]
I created the config.ini in the root folder using your example. The config.ini file is not being found when run.
Any thoughts?

Opening and Verifying Configuration File.
Config file missing, Exiting...
Press any key to continue . . .

**Comment by deathbybandaid** [comment]
That's what I forgot to document

`python3 main.py --config_file=` and the path to the config file

**Comment by deathbybandaid** [comment]
Added instruction to the wiki. Thanks for reminding me.

I got caught up doing some improvements to the code as well as making that code work across the other repos in the git organization.

Today, I hammered out some changes to make the input source easier to swap out as well as the scheduling.

**Comment by tharris9d** [comment]
Awesome, Thanks
